name: tekartik_aliyun_tablestore
description: A starting point for Dart libraries or applications.
version: 0.2.3
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.10.0

dependencies:
  path: ">=1.9.0"
  meta: ">=1.15.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.5.5'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.10.14'
  cv: ">=1.1.0+4"
dev_dependencies:
  test: ">=1.24.0"
resolution: workspace
