name: tekartik_aliyun_fc_http
description: A starting point for Dart libraries or applications.
version: 0.1.5
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
    version: '>=0.2.0+2'
  tekartik_aliyun_fc:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/fc
    version: '>=0.1.1'
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.5.5'
  synchronized:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
    version: '>=0.10.14'
dev_dependencies:
  test: ">=1.24.0"

resolution: workspace
